
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action DokumentiAction;
	
	private global::Gtk.Action SuradniciAction;
	
	private global::Gtk.Action ArtikliAction;
	
	private global::Gtk.Action StatistikaAction;
	
	private global::Gtk.Action PrimkeAction;
	
	private global::Gtk.Action OtpremniceAction;
	
	private global::Gtk.Action DobavljaiAction;
	
	private global::Gtk.Action PrijevozniciAction;
	
	private global::Gtk.Action ZaposleniciAction;
	
	private global::Gtk.Action MjestaAction;
	
	private global::Gtk.Action PregledAction;
	
	private global::Gtk.Action KategorijeAction;
	
	private global::Gtk.Action JediniceMjereAction;
	
	private global::Gtk.Action EvidencijaPromjenaAction;
	
	private global::Gtk.Action ProgramAction;
	
	private global::Gtk.Action IzlazAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.DokumentiAction = new global::Gtk.Action ("DokumentiAction", global::Mono.Unix.Catalog.GetString ("Dokumenti"), null, null);
		this.DokumentiAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dokumenti");
		w1.Add (this.DokumentiAction, null);
		this.SuradniciAction = new global::Gtk.Action ("SuradniciAction", global::Mono.Unix.Catalog.GetString ("Suradnici"), null, null);
		this.SuradniciAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Suradnici");
		w1.Add (this.SuradniciAction, null);
		this.ArtikliAction = new global::Gtk.Action ("ArtikliAction", global::Mono.Unix.Catalog.GetString ("Artikli"), null, null);
		this.ArtikliAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Artikli");
		w1.Add (this.ArtikliAction, null);
		this.StatistikaAction = new global::Gtk.Action ("StatistikaAction", global::Mono.Unix.Catalog.GetString ("Statistika"), null, null);
		this.StatistikaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Statistika");
		w1.Add (this.StatistikaAction, null);
		this.PrimkeAction = new global::Gtk.Action ("PrimkeAction", global::Mono.Unix.Catalog.GetString ("Primke"), null, null);
		this.PrimkeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Primke");
		w1.Add (this.PrimkeAction, null);
		this.OtpremniceAction = new global::Gtk.Action ("OtpremniceAction", global::Mono.Unix.Catalog.GetString ("Otpremnice"), null, null);
		this.OtpremniceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Otpremnice");
		w1.Add (this.OtpremniceAction, null);
		this.DobavljaiAction = new global::Gtk.Action ("DobavljaiAction", global::Mono.Unix.Catalog.GetString ("Dobavljači"), null, null);
		this.DobavljaiAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dobavljači");
		w1.Add (this.DobavljaiAction, null);
		this.PrijevozniciAction = new global::Gtk.Action ("PrijevozniciAction", global::Mono.Unix.Catalog.GetString ("Prijevoznici"), null, null);
		this.PrijevozniciAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Prijevoznici");
		w1.Add (this.PrijevozniciAction, null);
		this.ZaposleniciAction = new global::Gtk.Action ("ZaposleniciAction", global::Mono.Unix.Catalog.GetString ("Zaposlenici"), null, null);
		this.ZaposleniciAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Zaposlenici");
		w1.Add (this.ZaposleniciAction, null);
		this.MjestaAction = new global::Gtk.Action ("MjestaAction", global::Mono.Unix.Catalog.GetString ("Mjesta"), null, null);
		this.MjestaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Mjesta");
		w1.Add (this.MjestaAction, null);
		this.PregledAction = new global::Gtk.Action ("PregledAction", global::Mono.Unix.Catalog.GetString ("Pregled"), null, null);
		this.PregledAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pregled");
		w1.Add (this.PregledAction, null);
		this.KategorijeAction = new global::Gtk.Action ("KategorijeAction", global::Mono.Unix.Catalog.GetString ("Kategorije"), null, null);
		this.KategorijeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Kategorije");
		w1.Add (this.KategorijeAction, null);
		this.JediniceMjereAction = new global::Gtk.Action ("JediniceMjereAction", global::Mono.Unix.Catalog.GetString ("Jedinice mjere"), null, null);
		this.JediniceMjereAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Jedinice mjere");
		w1.Add (this.JediniceMjereAction, null);
		this.EvidencijaPromjenaAction = new global::Gtk.Action ("EvidencijaPromjenaAction", global::Mono.Unix.Catalog.GetString ("Evidencija promjena"), null, null);
		this.EvidencijaPromjenaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Evidencija promjena");
		w1.Add (this.EvidencijaPromjenaAction, null);
		this.ProgramAction = new global::Gtk.Action ("ProgramAction", global::Mono.Unix.Catalog.GetString ("Program"), null, null);
		this.ProgramAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Program");
		w1.Add (this.ProgramAction, null);
		this.IzlazAction = new global::Gtk.Action ("IzlazAction", global::Mono.Unix.Catalog.GetString ("Izlaz"), null, null);
		this.IzlazAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Izlaz");
		w1.Add (this.IzlazAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='ProgramAction' action='ProgramAction'><menuitem name='IzlazAction' action='IzlazAction'/></menu><menu name='DokumentiAction' action='DokumentiAction'><menuitem name='PrimkeAction' action='PrimkeAction'/><menuitem name='OtpremniceAction' action='OtpremniceAction'/></menu><menu name='SuradniciAction' action='SuradniciAction'><menuitem name='DobavljaiAction' action='DobavljaiAction'/><menuitem name='PrijevozniciAction' action='PrijevozniciAction'/><menuitem name='ZaposleniciAction' action='ZaposleniciAction'/><menuitem name='MjestaAction' action='MjestaAction'/></menu><menu name='ArtikliAction' action='ArtikliAction'><menuitem name='PregledAction' action='PregledAction'/><menuitem name='KategorijeAction' action='KategorijeAction'/><menuitem name='JediniceMjereAction' action='JediniceMjereAction'/></menu><menu name='StatistikaAction' action='StatistikaAction'><menuitem name='EvidencijaPromjenaAction' action='EvidencijaPromjenaAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 855;
		this.DefaultHeight = 623;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.DobavljaiAction.Activated += new global::System.EventHandler (this.dobavljaci_onClick);
		this.PrijevozniciAction.Activated += new global::System.EventHandler (this.prijevoznici_onClick);
		this.ZaposleniciAction.Activated += new global::System.EventHandler (this.zaposlenici_onClick);
		this.MjestaAction.Activated += new global::System.EventHandler (this.mjesta_onClick);
		this.PregledAction.Activated += new global::System.EventHandler (this.onClick_Pregled);
		this.KategorijeAction.Activated += new global::System.EventHandler (this.btnKategorije_onClick);
		this.IzlazAction.Activated += new global::System.EventHandler (this.onClick_Izlaz);
	}
}
