
// This file has been generated by the GUI designer. Do not modify.
namespace MyStockManager
{
	public partial class PrijevoznikWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button btnNoviPrijevoznik;
		
		private global::Gtk.Button btnUrediPrijevoznika;
		
		private global::Gtk.Button btnObrisiPrijevoznik;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView nodeview1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button btnZatvori;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyStockManager.PrijevoznikWindow
			this.Name = "MyStockManager.PrijevoznikWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Prijevoznici");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MyStockManager.PrijevoznikWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnNoviPrijevoznik = new global::Gtk.Button ();
			this.btnNoviPrijevoznik.CanFocus = true;
			this.btnNoviPrijevoznik.Name = "btnNoviPrijevoznik";
			this.btnNoviPrijevoznik.UseUnderline = true;
			this.btnNoviPrijevoznik.Label = global::Mono.Unix.Catalog.GetString (" Novi ");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.SmallToolbar);
			this.btnNoviPrijevoznik.Image = w1;
			this.hbox1.Add (this.btnNoviPrijevoznik);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnNoviPrijevoznik]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(15));
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnUrediPrijevoznika = new global::Gtk.Button ();
			this.btnUrediPrijevoznika.CanFocus = true;
			this.btnUrediPrijevoznika.Name = "btnUrediPrijevoznika";
			this.btnUrediPrijevoznika.UseUnderline = true;
			this.btnUrediPrijevoznika.Label = global::Mono.Unix.Catalog.GetString (" Uredi ");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.SmallToolbar);
			this.btnUrediPrijevoznika.Image = w3;
			this.hbox1.Add (this.btnUrediPrijevoznika);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnUrediPrijevoznika]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(15));
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnObrisiPrijevoznik = new global::Gtk.Button ();
			this.btnObrisiPrijevoznik.CanFocus = true;
			this.btnObrisiPrijevoznik.Name = "btnObrisiPrijevoznik";
			this.btnObrisiPrijevoznik.UseUnderline = true;
			this.btnObrisiPrijevoznik.Label = global::Mono.Unix.Catalog.GetString (" Obriši ");
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.SmallToolbar);
			this.btnObrisiPrijevoznik.Image = w5;
			this.hbox1.Add (this.btnObrisiPrijevoznik);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnObrisiPrijevoznik]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(15));
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(15));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView ();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add (this.nodeview1);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w9.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnZatvori = new global::Gtk.Button ();
			this.btnZatvori.CanFocus = true;
			this.btnZatvori.Name = "btnZatvori";
			this.btnZatvori.UseUnderline = true;
			this.btnZatvori.Label = global::Mono.Unix.Catalog.GetString ("Zatvori");
			this.hbox2.Add (this.btnZatvori);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnZatvori]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(15));
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 802;
			this.DefaultHeight = 300;
			this.Show ();
			this.btnZatvori.Clicked += new global::System.EventHandler (this.btnZatvori_onClick);
		}
	}
}
