
// This file has been generated by the GUI designer. Do not modify.
namespace MyStockManager
{
	public partial class KategorijaNewEditWindow
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry txtNaziv;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView txtOpis;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Button btnSpremi;
		
		private global::Gtk.Button btnOdustani;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyStockManager.KategorijaNewEditWindow
			this.Name = "MyStockManager.KategorijaNewEditWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Nova kategorija");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child MyStockManager.KategorijaNewEditWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.WidthRequest = 120;
			this.label1.Name = "label1";
			this.label1.Ypad = 15;
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Naziv:");
			this.hbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(15));
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtNaziv = new global::Gtk.Entry ();
			this.txtNaziv.CanFocus = true;
			this.txtNaziv.Name = "txtNaziv";
			this.txtNaziv.IsEditable = true;
			this.txtNaziv.InvisibleChar = '•';
			this.hbox3.Add (this.txtNaziv);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtNaziv]));
			w2.Position = 1;
			w2.Padding = ((uint)(15));
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 120;
			this.label2.Name = "label2";
			this.label2.Ypad = 15;
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Opis:");
			this.hbox4.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(15));
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtOpis = new global::Gtk.TextView ();
			this.txtOpis.CanFocus = true;
			this.txtOpis.Name = "txtOpis";
			this.GtkScrolledWindow.Add (this.txtOpis);
			this.hbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow]));
			w6.Position = 1;
			w6.Padding = ((uint)(15));
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnSpremi = new global::Gtk.Button ();
			this.btnSpremi.CanFocus = true;
			this.btnSpremi.Name = "btnSpremi";
			this.btnSpremi.UseUnderline = true;
			this.btnSpremi.Label = global::Mono.Unix.Catalog.GetString ("  Spremi  ");
			this.hbox6.Add (this.btnSpremi);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.btnSpremi]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			w8.Padding = ((uint)(15));
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnOdustani = new global::Gtk.Button ();
			this.btnOdustani.CanFocus = true;
			this.btnOdustani.Name = "btnOdustani";
			this.btnOdustani.UseUnderline = true;
			this.btnOdustani.Label = global::Mono.Unix.Catalog.GetString ("  Odustani  ");
			this.hbox6.Add (this.btnOdustani);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.btnOdustani]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			w9.Padding = ((uint)(15));
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(15));
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 718;
			this.DefaultHeight = 195;
			this.Show ();
			this.btnOdustani.Clicked += new global::System.EventHandler (this.btnOdustani_onClick);
			this.btnSpremi.Clicked += new global::System.EventHandler (this.btnSpremi_onClick);
		}
	}
}
