
// This file has been generated by the GUI designer. Do not modify.
namespace MyStockManager
{
	public partial class ArtiklNewEditWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry txtNaziv;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ComboBox cbKategorija;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView txtOpis;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry txtCijena;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry txtStanje;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry txtZaliheMin;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry txtZaliheMax;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.ComboBox cbJedinicaMjere;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Button btnSpremi;
		
		private global::Gtk.Button btnOdustani;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyStockManager.ArtiklNewEditWindow
			this.Name = "MyStockManager.ArtiklNewEditWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Novi artikl");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child MyStockManager.ArtiklNewEditWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.WidthRequest = 120;
			this.label1.Name = "label1";
			this.label1.Ypad = 15;
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Naziv artikla:");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(15));
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtNaziv = new global::Gtk.Entry ();
			this.txtNaziv.CanFocus = true;
			this.txtNaziv.Name = "txtNaziv";
			this.txtNaziv.IsEditable = true;
			this.txtNaziv.InvisibleChar = '•';
			this.hbox2.Add (this.txtNaziv);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtNaziv]));
			w2.Position = 1;
			w2.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 120;
			this.label2.Name = "label2";
			this.label2.Ypad = 15;
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Kategorija:");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(15));
			// Container child hbox3.Gtk.Box+BoxChild
			this.cbKategorija = global::Gtk.ComboBox.NewText ();
			this.cbKategorija.WidthRequest = 200;
			this.cbKategorija.Name = "cbKategorija";
			this.hbox3.Add (this.cbKategorija);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cbKategorija]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 120;
			this.label3.Name = "label3";
			this.label3.Ypad = 15;
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Opis:");
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(15));
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtOpis = new global::Gtk.TextView ();
			this.txtOpis.CanFocus = true;
			this.txtOpis.Name = "txtOpis";
			this.txtOpis.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.txtOpis);
			this.hbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow]));
			w9.Position = 1;
			w9.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 120;
			this.label4.Name = "label4";
			this.label4.Ypad = 15;
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Cijena (kn):");
			this.hbox5.Add (this.label4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label4]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(15));
			// Container child hbox5.Gtk.Box+BoxChild
			this.txtCijena = new global::Gtk.Entry ();
			this.txtCijena.CanFocus = true;
			this.txtCijena.Name = "txtCijena";
			this.txtCijena.IsEditable = true;
			this.txtCijena.InvisibleChar = '•';
			this.hbox5.Add (this.txtCijena);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.txtCijena]));
			w12.Position = 1;
			w12.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 120;
			this.label5.Name = "label5";
			this.label5.Ypad = 15;
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Stanje:");
			this.hbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label5]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			w14.Padding = ((uint)(15));
			// Container child hbox6.Gtk.Box+BoxChild
			this.txtStanje = new global::Gtk.Entry ();
			this.txtStanje.CanFocus = true;
			this.txtStanje.Name = "txtStanje";
			this.txtStanje.IsEditable = true;
			this.txtStanje.InvisibleChar = '•';
			this.hbox6.Add (this.txtStanje);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.txtStanje]));
			w15.Position = 1;
			w15.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 120;
			this.label6.Name = "label6";
			this.label6.Ypad = 15;
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Zalihe (min):");
			this.hbox7.Add (this.label6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(15));
			// Container child hbox7.Gtk.Box+BoxChild
			this.txtZaliheMin = new global::Gtk.Entry ();
			this.txtZaliheMin.CanFocus = true;
			this.txtZaliheMin.Name = "txtZaliheMin";
			this.txtZaliheMin.IsEditable = true;
			this.txtZaliheMin.InvisibleChar = '•';
			this.hbox7.Add (this.txtZaliheMin);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.txtZaliheMin]));
			w18.Position = 1;
			w18.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w19.Position = 5;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.WidthRequest = 120;
			this.label7.Name = "label7";
			this.label7.Ypad = 15;
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Zalihe (max):");
			this.hbox8.Add (this.label7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label7]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			w20.Padding = ((uint)(15));
			// Container child hbox8.Gtk.Box+BoxChild
			this.txtZaliheMax = new global::Gtk.Entry ();
			this.txtZaliheMax.CanFocus = true;
			this.txtZaliheMax.Name = "txtZaliheMax";
			this.txtZaliheMax.IsEditable = true;
			this.txtZaliheMax.InvisibleChar = '•';
			this.hbox8.Add (this.txtZaliheMax);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.txtZaliheMax]));
			w21.Position = 1;
			w21.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox8);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
			w22.Position = 6;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.WidthRequest = 120;
			this.label8.Name = "label8";
			this.label8.Ypad = 15;
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Jedinica mjere:");
			this.hbox9.Add (this.label8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label8]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(15));
			// Container child hbox9.Gtk.Box+BoxChild
			this.cbJedinicaMjere = global::Gtk.ComboBox.NewText ();
			this.cbJedinicaMjere.WidthRequest = 200;
			this.cbJedinicaMjere.Name = "cbJedinicaMjere";
			this.hbox9.Add (this.cbJedinicaMjere);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.cbJedinicaMjere]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(15));
			this.vbox1.Add (this.hbox9);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox9]));
			w25.Position = 7;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.btnSpremi = new global::Gtk.Button ();
			this.btnSpremi.WidthRequest = 80;
			this.btnSpremi.CanFocus = true;
			this.btnSpremi.Name = "btnSpremi";
			this.btnSpremi.UseUnderline = true;
			this.btnSpremi.Label = global::Mono.Unix.Catalog.GetString ("Spremi");
			this.hbox10.Add (this.btnSpremi);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.btnSpremi]));
			w26.PackType = ((global::Gtk.PackType)(1));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			w26.Padding = ((uint)(15));
			// Container child hbox10.Gtk.Box+BoxChild
			this.btnOdustani = new global::Gtk.Button ();
			this.btnOdustani.WidthRequest = 80;
			this.btnOdustani.CanFocus = true;
			this.btnOdustani.Name = "btnOdustani";
			this.btnOdustani.UseUnderline = true;
			this.btnOdustani.Label = global::Mono.Unix.Catalog.GetString ("Odustani");
			this.hbox10.Add (this.btnOdustani);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.btnOdustani]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox1.Add (this.hbox10);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox10]));
			w28.PackType = ((global::Gtk.PackType)(1));
			w28.Position = 8;
			w28.Expand = false;
			w28.Fill = false;
			w28.Padding = ((uint)(15));
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 644;
			this.DefaultHeight = 511;
			this.Show ();
			this.btnOdustani.Clicked += new global::System.EventHandler (this.btnOdustani_onClick);
			this.btnSpremi.Clicked += new global::System.EventHandler (this.btnSpremi_onClick);
		}
	}
}
