
// This file has been generated by the GUI designer. Do not modify.
namespace MyStockManager
{
	public partial class ArtikliWindow
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button btnNoviArtikl;
		
		private global::Gtk.Button btnUredi;
		
		private global::Gtk.Button btnObrisi;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView nodeview1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button btnZatvori;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyStockManager.ArtikliWindow
			this.Name = "MyStockManager.ArtikliWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Artikli");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child MyStockManager.ArtikliWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnNoviArtikl = new global::Gtk.Button ();
			this.btnNoviArtikl.CanFocus = true;
			this.btnNoviArtikl.Name = "btnNoviArtikl";
			this.btnNoviArtikl.UseUnderline = true;
			this.btnNoviArtikl.Label = global::Mono.Unix.Catalog.GetString ("Novi artikl");
			this.hbox2.Add (this.btnNoviArtikl);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnNoviArtikl]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(15));
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnUredi = new global::Gtk.Button ();
			this.btnUredi.CanFocus = true;
			this.btnUredi.Name = "btnUredi";
			this.btnUredi.UseUnderline = true;
			this.btnUredi.Label = global::Mono.Unix.Catalog.GetString ("Uredi označenog");
			this.hbox2.Add (this.btnUredi);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnUredi]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(15));
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnObrisi = new global::Gtk.Button ();
			this.btnObrisi.CanFocus = true;
			this.btnObrisi.Name = "btnObrisi";
			this.btnObrisi.UseUnderline = true;
			this.btnObrisi.Label = global::Mono.Unix.Catalog.GetString ("Obriši označenog");
			this.hbox2.Add (this.btnObrisi);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnObrisi]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(15));
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(15));
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView ();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add (this.nodeview1);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w6.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnZatvori = new global::Gtk.Button ();
			this.btnZatvori.CanFocus = true;
			this.btnZatvori.Name = "btnZatvori";
			this.btnZatvori.UseUnderline = true;
			this.btnZatvori.Label = global::Mono.Unix.Catalog.GetString ("Zatvori");
			this.hbox1.Add (this.btnZatvori);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnZatvori]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(15));
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			w8.Padding = ((uint)(15));
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 994;
			this.DefaultHeight = 575;
			this.Show ();
			this.btnNoviArtikl.Clicked += new global::System.EventHandler (this.btnUredi_onClick);
			this.btnZatvori.Clicked += new global::System.EventHandler (this.btnZatvori_onClick);
		}
	}
}
