
// This file has been generated by the GUI designer. Do not modify.
namespace MyStockManager
{
	public partial class ZaposlenikWindow
	{
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button btnNoviZaposlenik;
		
		private global::Gtk.Button btnUrediZaposlenika;
		
		private global::Gtk.Button btnObrisi;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView nodeview1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Button btnZatvori;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyStockManager.ZaposlenikWindow
			this.Name = "MyStockManager.ZaposlenikWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ZaposlenikWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MyStockManager.ZaposlenikWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnNoviZaposlenik = new global::Gtk.Button ();
			this.btnNoviZaposlenik.CanFocus = true;
			this.btnNoviZaposlenik.Name = "btnNoviZaposlenik";
			this.btnNoviZaposlenik.UseUnderline = true;
			this.btnNoviZaposlenik.Label = global::Mono.Unix.Catalog.GetString (" Novi ");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.SmallToolbar);
			this.btnNoviZaposlenik.Image = w1;
			this.hbox3.Add (this.btnNoviZaposlenik);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnNoviZaposlenik]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(15));
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnUrediZaposlenika = new global::Gtk.Button ();
			this.btnUrediZaposlenika.CanFocus = true;
			this.btnUrediZaposlenika.Name = "btnUrediZaposlenika";
			this.btnUrediZaposlenika.UseUnderline = true;
			this.btnUrediZaposlenika.Label = global::Mono.Unix.Catalog.GetString (" Uredi ");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.SmallToolbar);
			this.btnUrediZaposlenika.Image = w3;
			this.hbox3.Add (this.btnUrediZaposlenika);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnUrediZaposlenika]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(15));
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnObrisi = new global::Gtk.Button ();
			this.btnObrisi.CanFocus = true;
			this.btnObrisi.Name = "btnObrisi";
			this.btnObrisi.UseUnderline = true;
			this.btnObrisi.Label = global::Mono.Unix.Catalog.GetString (" Obriši ");
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.SmallToolbar);
			this.btnObrisi.Image = w5;
			this.hbox3.Add (this.btnObrisi);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnObrisi]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(15));
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(15));
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(15));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView ();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add (this.nodeview1);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
			w9.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnZatvori = new global::Gtk.Button ();
			this.btnZatvori.CanFocus = true;
			this.btnZatvori.Name = "btnZatvori";
			this.btnZatvori.UseUnderline = true;
			this.btnZatvori.Label = global::Mono.Unix.Catalog.GetString ("Zatvori");
			this.hbox4.Add (this.btnZatvori);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnZatvori]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(15));
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(15));
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 495;
			this.DefaultHeight = 300;
			this.Show ();
			this.btnZatvori.Clicked += new global::System.EventHandler (this.btnZatvori_onClick);
		}
	}
}
